#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/e2e/postgres-s3-rds-drill-resources.sh ensure|delete|verify [flags]

Stack-owned lifecycle helper for the PostgreSQL S3 to RDS restore drill.

Flags:
  --env-file PATH   Env file written/read by the stack (default: docs/showcase/postgres-s3-rds-drill/runtime/manual.env)
  --workdir PATH    Runtime directory (default: docs/showcase/postgres-s3-rds-drill/runtime)
  --region REGION   AWS region (default: AWS_REGION/AWS_DEFAULT_REGION/us-east-1)
EOF
}

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

action="${1:-}"
if [[ -z "${action}" || "${action}" == "-h" || "${action}" == "--help" ]]; then
  usage
  exit 0
fi
shift || true

workdir="${WORKDIR:-${repo_root}/docs/showcase/postgres-s3-rds-drill/runtime}"
env_file="${TORQUE_AWS_RDS_E2E_ENV_FILE:-${workdir}/manual.env}"
region="${AWS_REGION:-${AWS_DEFAULT_REGION:-}}"

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --env-file)
      env_file="$2"
      shift 2
      ;;
    --workdir)
      workdir="$2"
      shift 2
      ;;
    --region)
      region="$2"
      shift 2
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${region}" ]]; then
  region="$(aws configure get region 2>/dev/null || true)"
fi
if [[ -z "${region}" ]]; then
  region="us-east-1"
fi
export AWS_REGION="${region}"

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "missing required command: $1" >&2
    exit 1
  }
}

source_env_file() {
  [[ -f "${env_file}" ]] || return 1
  set -a
  # shellcheck disable=SC1090
  source "${env_file}"
  set +a
}

source_ready() {
  [[ -n "${TORQUE_DEMO_SOURCE_CONTAINER:-}" ]] || return 1
  [[ -n "${TORQUE_DEMO_SOURCE_PGPORT:-}" ]] || return 1
  [[ -n "${TORQUE_DEMO_SOURCE_PGPASSWORD:-}" ]] || return 1
  [[ "$(docker inspect -f '{{.State.Running}}' "${TORQUE_DEMO_SOURCE_CONTAINER}" 2>/dev/null || true)" == "true" ]] || return 1
  PGPASSWORD="${TORQUE_DEMO_SOURCE_PGPASSWORD}" psql \
    -h "${TORQUE_DEMO_SOURCE_PGHOST:-127.0.0.1}" \
    -p "${TORQUE_DEMO_SOURCE_PGPORT}" \
    -U postgres \
    -d keycloak \
    -At \
    -c "select count(*) from realm where name = 'torque'" 2>/dev/null | grep -qx '1'
}

s3_ready() {
  [[ -n "${TORQUE_DEMO_S3_BUCKET:-}" ]] || return 1
  aws s3api head-bucket --bucket "${TORQUE_DEMO_S3_BUCKET}" --region "${region}" >/dev/null 2>&1
}

rds_ready() {
  [[ -n "${TORQUE_DEMO_RDS_INSTANCE:-}" ]] || return 1
  [[ "$(aws rds describe-db-instances \
    --db-instance-identifier "${TORQUE_DEMO_RDS_INSTANCE}" \
    --query 'DBInstances[0].DBInstanceStatus' \
    --output text \
    --region "${region}" 2>/dev/null || true)" == "available" ]]
}

resources_ready() {
  source_ready && s3_ready && rds_ready
}

write_env_file() {
  mkdir -p "$(dirname "${env_file}")"
  umask 077
  {
    printf '%s\n' '# Local ignored env file generated by torque stack apply.'
    printf '%s\n' '# Source from the repo root with:'
    printf '%s\n' '#   set -a; source docs/showcase/postgres-s3-rds-drill/runtime/manual.env; set +a'
    printf 'export AWS_REGION=%q\n' "${region}"
    printf 'export TORQUE_DEMO_SOURCE_PGHOST=%q\n' "127.0.0.1"
    printf 'export TORQUE_DEMO_SOURCE_PGPORT=%q\n' "${source_port}"
    printf 'export TORQUE_DEMO_SOURCE_PGPASSWORD=%q\n' "${source_password}"
    printf 'export TORQUE_DEMO_S3_BUCKET=%q\n' "${bucket}"
    printf 'export TORQUE_DEMO_S3_PREFIX=%q\n' "${prefix}"
    printf 'export TORQUE_DEMO_RDS_ENDPOINT=%q\n' "${rds_endpoint}"
    printf 'export TORQUE_DEMO_RDS_PASSWORD=%q\n' "${rds_password}"
    printf 'export TORQUE_DEMO_RDS_INSTANCE=%q\n' "${rds_id}"
    printf 'export TORQUE_DEMO_RDS_SUBNET_GROUP=%q\n' "${subnet_group}"
    printf 'export TORQUE_DEMO_RDS_SECURITY_GROUP_ID=%q\n' "${sg_id}"
    printf 'export TORQUE_DEMO_SOURCE_CONTAINER=%q\n' "${source_container}"
  } >"${env_file}"
  chmod 600 "${env_file}"
}

delete_resources() {
  set +e
  if source_env_file; then
    docker rm -f "${TORQUE_DEMO_SOURCE_CONTAINER:-}" >/dev/null 2>&1

    if [[ -n "${TORQUE_DEMO_RDS_INSTANCE:-}" ]]; then
      aws rds delete-db-instance \
        --db-instance-identifier "${TORQUE_DEMO_RDS_INSTANCE}" \
        --skip-final-snapshot \
        --delete-automated-backups \
        --region "${region}" >/dev/null 2>&1
      aws rds wait db-instance-deleted \
        --db-instance-identifier "${TORQUE_DEMO_RDS_INSTANCE}" \
        --region "${region}" >/dev/null 2>&1
    fi

    if [[ -n "${TORQUE_DEMO_RDS_SUBNET_GROUP:-}" ]]; then
      aws rds delete-db-subnet-group \
        --db-subnet-group-name "${TORQUE_DEMO_RDS_SUBNET_GROUP}" \
        --region "${region}" >/dev/null 2>&1
    fi

    if [[ -n "${TORQUE_DEMO_RDS_SECURITY_GROUP_ID:-}" ]]; then
      for _ in $(seq 1 30); do
        aws ec2 delete-security-group \
          --group-id "${TORQUE_DEMO_RDS_SECURITY_GROUP_ID}" \
          --region "${region}" >/dev/null 2>&1 && break
        sleep 5
      done
    fi

    if [[ -n "${TORQUE_DEMO_S3_BUCKET:-}" ]]; then
      aws s3 rm "s3://${TORQUE_DEMO_S3_BUCKET}" --recursive --region "${region}" >/dev/null 2>&1
      uploads="$(aws s3api list-multipart-uploads \
        --bucket "${TORQUE_DEMO_S3_BUCKET}" \
        --region "${region}" \
        --query 'Uploads[].[Key,UploadId]' \
        --output text 2>/dev/null || true)"
      while read -r key upload_id; do
        [[ -n "${key:-}" && -n "${upload_id:-}" ]] && \
          aws s3api abort-multipart-upload \
            --bucket "${TORQUE_DEMO_S3_BUCKET}" \
            --key "${key}" \
            --upload-id "${upload_id}" \
            --region "${region}" >/dev/null 2>&1
      done <<<"${uploads}"
      aws s3api delete-bucket \
        --bucket "${TORQUE_DEMO_S3_BUCKET}" \
        --region "${region}" >/dev/null 2>&1
    fi
  fi
  set -e
}

verify_deleted() {
  local failed=0
  if [[ -n "${TORQUE_DEMO_SOURCE_CONTAINER:-}" ]] && docker inspect "${TORQUE_DEMO_SOURCE_CONTAINER}" >/dev/null 2>&1; then
    echo "source container still exists: ${TORQUE_DEMO_SOURCE_CONTAINER}" >&2
    failed=1
  fi
  if [[ -n "${TORQUE_DEMO_RDS_INSTANCE:-}" ]] && aws rds describe-db-instances --db-instance-identifier "${TORQUE_DEMO_RDS_INSTANCE}" --region "${region}" >/dev/null 2>&1; then
    echo "RDS instance still exists: ${TORQUE_DEMO_RDS_INSTANCE}" >&2
    failed=1
  fi
  if [[ -n "${TORQUE_DEMO_RDS_SUBNET_GROUP:-}" ]] && aws rds describe-db-subnet-groups --db-subnet-group-name "${TORQUE_DEMO_RDS_SUBNET_GROUP}" --region "${region}" >/dev/null 2>&1; then
    echo "RDS subnet group still exists: ${TORQUE_DEMO_RDS_SUBNET_GROUP}" >&2
    failed=1
  fi
  if [[ -n "${TORQUE_DEMO_RDS_SECURITY_GROUP_ID:-}" ]] && aws ec2 describe-security-groups --group-ids "${TORQUE_DEMO_RDS_SECURITY_GROUP_ID}" --region "${region}" >/dev/null 2>&1; then
    echo "security group still exists: ${TORQUE_DEMO_RDS_SECURITY_GROUP_ID}" >&2
    failed=1
  fi
  if [[ -n "${TORQUE_DEMO_S3_BUCKET:-}" ]] && aws s3api head-bucket --bucket "${TORQUE_DEMO_S3_BUCKET}" --region "${region}" >/dev/null 2>&1; then
    echo "S3 bucket still exists: ${TORQUE_DEMO_S3_BUCKET}" >&2
    failed=1
  fi
  return "${failed}"
}

ensure_resources() {
  require_cmd aws
  require_cmd curl
  require_cmd docker
  require_cmd psql
  require_cmd python3

  mkdir -p "${workdir}/backups"
  if source_env_file && resources_ready; then
    echo "reusing live PostgreSQL S3/RDS drill resources from ${env_file}"
    exit 0
  fi

  if [[ -f "${env_file}" ]]; then
    echo "existing env file is stale; deleting stale resources before recreate"
    delete_resources || true
  fi

  suffix="$(python3 - <<'PY'
import secrets
print(secrets.token_hex(5))
PY
)"
  bucket="torque-pg-rds-drill-${suffix}"
  prefix="postgres-rds-drill/${suffix}"
  rds_id="torque-pg-rds-${suffix}"
  subnet_group="torque-pg-rds-${suffix}"
  sg_name="torque-pg-rds-${suffix}"
  source_container="torque-pg-source-${suffix}"
  sg_id=""
  rds_endpoint=""
  source_port="$(python3 - <<'PY'
import socket
s = socket.socket()
s.bind(("127.0.0.1", 0))
print(s.getsockname()[1])
s.close()
PY
)"
  source_password="$(python3 - <<'PY'
import secrets
print("TqSrc" + secrets.token_hex(12) + "9")
PY
)"
  rds_password="$(python3 - <<'PY'
import secrets
print("TqRds" + secrets.token_hex(12) + "9")
PY
)"
  write_env_file

  echo "creating disposable S3 bucket ${bucket} in ${region}"
  if [[ "${region}" == "us-east-1" ]]; then
    aws s3api create-bucket --bucket "${bucket}" --region "${region}" >"${workdir}/aws-s3-create-bucket.json"
  else
    aws s3api create-bucket \
      --bucket "${bucket}" \
      --region "${region}" \
      --create-bucket-configuration LocationConstraint="${region}" >"${workdir}/aws-s3-create-bucket.json"
  fi

  echo "starting disposable source PostgreSQL container on 127.0.0.1:${source_port}"
  docker run -d \
    --name "${source_container}" \
    -e POSTGRES_PASSWORD="${source_password}" \
    -p "127.0.0.1:${source_port}:5432" \
    postgres:16-alpine >"${workdir}/source-container.id"

  for _ in $(seq 1 90); do
    if PGPASSWORD="${source_password}" psql -h 127.0.0.1 -p "${source_port}" -U postgres -d postgres -c "select 1" >/dev/null 2>&1; then
      break
    fi
    sleep 2
  done
  PGPASSWORD="${source_password}" psql -h 127.0.0.1 -p "${source_port}" -U postgres -d postgres -v ON_ERROR_STOP=1 \
    -c "create database keycloak" >"${workdir}/source-create-db.log"
  PGPASSWORD="${source_password}" psql -h 127.0.0.1 -p "${source_port}" -U postgres -d keycloak -v ON_ERROR_STOP=1 \
    -c "create table realm(id text primary key, name text not null); insert into realm(id, name) values ('torque', 'torque');" >"${workdir}/source-seed.log"

  vpc_id="$(aws ec2 describe-vpcs \
    --filters Name=is-default,Values=true \
    --query 'Vpcs[0].VpcId' \
    --output text \
    --region "${region}")"
  if [[ -z "${vpc_id}" || "${vpc_id}" == "None" ]]; then
    echo "no default VPC found in ${region}; cannot create public disposable RDS demo" >&2
    exit 1
  fi
  read -r -a subnet_ids <<<"$(aws ec2 describe-subnets \
    --filters Name=vpc-id,Values="${vpc_id}" \
    --query 'Subnets[].SubnetId' \
    --output text \
    --region "${region}")"
  if [[ "${#subnet_ids[@]}" -lt 2 ]]; then
    echo "default VPC ${vpc_id} has fewer than two subnets; RDS subnet group requires at least two" >&2
    exit 1
  fi

  client_ip="$(curl -fsS https://checkip.amazonaws.com | tr -d '[:space:]')"
  echo "creating RDS subnet group and security group in ${vpc_id}"
  aws rds create-db-subnet-group \
    --db-subnet-group-name "${subnet_group}" \
    --db-subnet-group-description "Torque PostgreSQL S3 RDS drill ${suffix}" \
    --subnet-ids "${subnet_ids[@]}" \
    --tags Key=managed-by,Value=torque Key=torque-demo,Value=postgres-s3-rds-drill \
    --region "${region}" >"${workdir}/aws-rds-subnet-group.json"

  sg_id="$(aws ec2 create-security-group \
    --group-name "${sg_name}" \
    --description "Torque PostgreSQL S3 RDS drill ${suffix}" \
    --vpc-id "${vpc_id}" \
    --query GroupId \
    --output text \
    --region "${region}")"
  write_env_file
  aws ec2 authorize-security-group-ingress \
    --group-id "${sg_id}" \
    --protocol tcp \
    --port 5432 \
    --cidr "${client_ip}/32" \
    --region "${region}" >"${workdir}/aws-rds-sg-ingress.json"

  db_class=""
  for candidate in db.t4g.micro db.t3.micro db.t4g.small db.t3.small; do
    count="$(aws rds describe-orderable-db-instance-options \
      --engine postgres \
      --db-instance-class "${candidate}" \
      --query 'length(OrderableDBInstanceOptions)' \
      --output text \
      --region "${region}" 2>/dev/null || echo 0)"
    if [[ "${count}" != "0" ]]; then
      db_class="${candidate}"
      break
    fi
  done
  if [[ -z "${db_class}" ]]; then
    echo "could not find an orderable small PostgreSQL RDS class in ${region}" >&2
    exit 1
  fi

  echo "creating disposable RDS PostgreSQL instance ${rds_id} (${db_class}); this can take several minutes"
  aws rds create-db-instance \
    --db-instance-identifier "${rds_id}" \
    --db-instance-class "${db_class}" \
    --engine postgres \
    --allocated-storage 20 \
    --master-username torque_demo \
    --master-user-password "${rds_password}" \
    --db-subnet-group-name "${subnet_group}" \
    --vpc-security-group-ids "${sg_id}" \
    --publicly-accessible \
    --backup-retention-period 0 \
    --no-deletion-protection \
    --tags Key=managed-by,Value=torque Key=torque-demo,Value=postgres-s3-rds-drill \
    --region "${region}" >"${workdir}/aws-rds-create.json"
  aws rds wait db-instance-available --db-instance-identifier "${rds_id}" --region "${region}"
  rds_endpoint="$(aws rds describe-db-instances \
    --db-instance-identifier "${rds_id}" \
    --query 'DBInstances[0].Endpoint.Address' \
    --output text \
    --region "${region}")"
  echo "RDS endpoint is ready"

  write_env_file
  echo "manual env written to ${env_file}"
}

case "${action}" in
  ensure)
    ensure_resources
    ;;
  delete)
    source_env_file || {
      echo "no env file at ${env_file}; nothing to delete"
      exit 0
    }
    delete_resources
    verify_deleted
    rm -f "${env_file}"
    echo "PostgreSQL S3/RDS drill resources deleted"
    ;;
  verify)
    source_env_file
    resources_ready
    echo "PostgreSQL S3/RDS drill resources are ready"
    ;;
  *)
    echo "unknown action: ${action}" >&2
    usage >&2
    exit 2
    ;;
esac
