name: Bug report
description: Report something that is broken or unexpected in ktl.
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please include enough detail to reproduce.

        Before filing:
        - Search existing issues (including closed).
        - If this is a usage question, consider the "Support question" template instead.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight
      options:
        - label: I searched existing issues and didn’t find a duplicate.
          required: true
        - label: I can reproduce this on the latest `main` (or a recent release).
          required: false

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you see? Include error messages.
      placeholder: "ktl apply ... fails with ..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide the exact commands and inputs (redact secrets).
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant `ktl` output (redact secrets). Prefer text over screenshots.
      render: shell
    validations:
      required: false

  - type: textarea
    id: version
    attributes:
      label: Version and environment
      description: Paste `ktl --version` (or `./bin/ktl --version`), OS, and any relevant tool versions (kubectl/helm/docker).
      placeholder: |
        ktl:
        go:
        os/arch:
        kubectl:
        helm:
        docker/buildkit:
      render: text
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else that might help (cluster type, chart size, CI runner, etc.).
    validations:
      required: false

