// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/ktl/api/v1/agent.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PodQuery          string                 `protobuf:"bytes,1,opt,name=pod_query,json=podQuery,proto3" json:"pod_query,omitempty"`
	Namespaces        []string               `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	AllNamespaces     bool                   `protobuf:"varint,3,opt,name=all_namespaces,json=allNamespaces,proto3" json:"all_namespaces,omitempty"`
	LabelSelector     string                 `protobuf:"bytes,4,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	FieldSelector     string                 `protobuf:"bytes,5,opt,name=field_selector,json=fieldSelector,proto3" json:"field_selector,omitempty"`
	Containers        []string               `protobuf:"bytes,6,rep,name=containers,proto3" json:"containers,omitempty"`
	ExcludeContainers []string               `protobuf:"bytes,7,rep,name=exclude_containers,json=excludeContainers,proto3" json:"exclude_containers,omitempty"`
	ExcludePods       []string               `protobuf:"bytes,8,rep,name=exclude_pods,json=excludePods,proto3" json:"exclude_pods,omitempty"`
	HighlightTerms    []string               `protobuf:"bytes,9,rep,name=highlight_terms,json=highlightTerms,proto3" json:"highlight_terms,omitempty"`
	IncludeEvents     bool                   `protobuf:"varint,10,opt,name=include_events,json=includeEvents,proto3" json:"include_events,omitempty"`
	EventsOnly        bool                   `protobuf:"varint,11,opt,name=events_only,json=eventsOnly,proto3" json:"events_only,omitempty"`
	TailLines         int64                  `protobuf:"varint,12,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	Follow            bool                   `protobuf:"varint,13,opt,name=follow,proto3" json:"follow,omitempty"`
	Timestamps        bool                   `protobuf:"varint,14,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	Template          string                 `protobuf:"bytes,15,opt,name=template,proto3" json:"template,omitempty"`
	KubeContext       string                 `protobuf:"bytes,16,opt,name=kube_context,json=kubeContext,proto3" json:"kube_context,omitempty"`
	KubeconfigPath    string                 `protobuf:"bytes,17,opt,name=kubeconfig_path,json=kubeconfigPath,proto3" json:"kubeconfig_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetPodQuery() string {
	if x != nil {
		return x.PodQuery
	}
	return ""
}

func (x *LogRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *LogRequest) GetAllNamespaces() bool {
	if x != nil {
		return x.AllNamespaces
	}
	return false
}

func (x *LogRequest) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

func (x *LogRequest) GetFieldSelector() string {
	if x != nil {
		return x.FieldSelector
	}
	return ""
}

func (x *LogRequest) GetContainers() []string {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *LogRequest) GetExcludeContainers() []string {
	if x != nil {
		return x.ExcludeContainers
	}
	return nil
}

func (x *LogRequest) GetExcludePods() []string {
	if x != nil {
		return x.ExcludePods
	}
	return nil
}

func (x *LogRequest) GetHighlightTerms() []string {
	if x != nil {
		return x.HighlightTerms
	}
	return nil
}

func (x *LogRequest) GetIncludeEvents() bool {
	if x != nil {
		return x.IncludeEvents
	}
	return false
}

func (x *LogRequest) GetEventsOnly() bool {
	if x != nil {
		return x.EventsOnly
	}
	return false
}

func (x *LogRequest) GetTailLines() int64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *LogRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogRequest) GetTimestamps() bool {
	if x != nil {
		return x.Timestamps
	}
	return false
}

func (x *LogRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *LogRequest) GetKubeContext() string {
	if x != nil {
		return x.KubeContext
	}
	return ""
}

func (x *LogRequest) GetKubeconfigPath() string {
	if x != nil {
		return x.KubeconfigPath
	}
	return ""
}

type LogLine struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNano  int64                  `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	FormattedTimestamp string                 `protobuf:"bytes,2,opt,name=formatted_timestamp,json=formattedTimestamp,proto3" json:"formatted_timestamp,omitempty"`
	Namespace          string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod                string                 `protobuf:"bytes,4,opt,name=pod,proto3" json:"pod,omitempty"`
	Container          string                 `protobuf:"bytes,5,opt,name=container,proto3" json:"container,omitempty"`
	Raw                string                 `protobuf:"bytes,6,opt,name=raw,proto3" json:"raw,omitempty"`
	Rendered           string                 `protobuf:"bytes,7,opt,name=rendered,proto3" json:"rendered,omitempty"`
	Source             string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	SourceGlyph        string                 `protobuf:"bytes,9,opt,name=source_glyph,json=sourceGlyph,proto3" json:"source_glyph,omitempty"`
	RenderedEqualsRaw  bool                   `protobuf:"varint,10,opt,name=rendered_equals_raw,json=renderedEqualsRaw,proto3" json:"rendered_equals_raw,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *LogLine) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogLine) GetFormattedTimestamp() string {
	if x != nil {
		return x.FormattedTimestamp
	}
	return ""
}

func (x *LogLine) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LogLine) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *LogLine) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *LogLine) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *LogLine) GetRendered() string {
	if x != nil {
		return x.Rendered
	}
	return ""
}

func (x *LogLine) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogLine) GetSourceGlyph() string {
	if x != nil {
		return x.SourceGlyph
	}
	return ""
}

func (x *LogLine) GetRenderedEqualsRaw() bool {
	if x != nil {
		return x.RenderedEqualsRaw
	}
	return false
}

type BuildOptions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ContextDir         string                 `protobuf:"bytes,1,opt,name=context_dir,json=contextDir,proto3" json:"context_dir,omitempty"`
	Dockerfile         string                 `protobuf:"bytes,2,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	Tags               []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Platforms          []string               `protobuf:"bytes,4,rep,name=platforms,proto3" json:"platforms,omitempty"`
	BuildArgs          []string               `protobuf:"bytes,5,rep,name=build_args,json=buildArgs,proto3" json:"build_args,omitempty"`
	Secrets            []string               `protobuf:"bytes,6,rep,name=secrets,proto3" json:"secrets,omitempty"`
	CacheFrom          []string               `protobuf:"bytes,7,rep,name=cache_from,json=cacheFrom,proto3" json:"cache_from,omitempty"`
	CacheTo            []string               `protobuf:"bytes,8,rep,name=cache_to,json=cacheTo,proto3" json:"cache_to,omitempty"`
	Push               bool                   `protobuf:"varint,9,opt,name=push,proto3" json:"push,omitempty"`
	Load               bool                   `protobuf:"varint,10,opt,name=load,proto3" json:"load,omitempty"`
	NoCache            bool                   `protobuf:"varint,11,opt,name=no_cache,json=noCache,proto3" json:"no_cache,omitempty"`
	Builder            string                 `protobuf:"bytes,12,opt,name=builder,proto3" json:"builder,omitempty"`
	CacheDir           string                 `protobuf:"bytes,13,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	Interactive        bool                   `protobuf:"varint,14,opt,name=interactive,proto3" json:"interactive,omitempty"`
	InteractiveShell   string                 `protobuf:"bytes,15,opt,name=interactive_shell,json=interactiveShell,proto3" json:"interactive_shell,omitempty"`
	BuildMode          string                 `protobuf:"bytes,16,opt,name=build_mode,json=buildMode,proto3" json:"build_mode,omitempty"`
	ComposeFiles       []string               `protobuf:"bytes,17,rep,name=compose_files,json=composeFiles,proto3" json:"compose_files,omitempty"`
	ComposeProfiles    []string               `protobuf:"bytes,18,rep,name=compose_profiles,json=composeProfiles,proto3" json:"compose_profiles,omitempty"`
	ComposeServices    []string               `protobuf:"bytes,19,rep,name=compose_services,json=composeServices,proto3" json:"compose_services,omitempty"`
	ComposeProject     string                 `protobuf:"bytes,20,opt,name=compose_project,json=composeProject,proto3" json:"compose_project,omitempty"`
	AuthFile           string                 `protobuf:"bytes,21,opt,name=auth_file,json=authFile,proto3" json:"auth_file,omitempty"`
	SandboxConfig      string                 `protobuf:"bytes,22,opt,name=sandbox_config,json=sandboxConfig,proto3" json:"sandbox_config,omitempty"`
	SandboxBin         string                 `protobuf:"bytes,23,opt,name=sandbox_bin,json=sandboxBin,proto3" json:"sandbox_bin,omitempty"`
	SandboxBinds       []string               `protobuf:"bytes,24,rep,name=sandbox_binds,json=sandboxBinds,proto3" json:"sandbox_binds,omitempty"`
	SandboxWorkdir     string                 `protobuf:"bytes,25,opt,name=sandbox_workdir,json=sandboxWorkdir,proto3" json:"sandbox_workdir,omitempty"`
	SandboxLogs        bool                   `protobuf:"varint,26,opt,name=sandbox_logs,json=sandboxLogs,proto3" json:"sandbox_logs,omitempty"`
	LogFile            string                 `protobuf:"bytes,27,opt,name=log_file,json=logFile,proto3" json:"log_file,omitempty"`
	RemoveIntermediate bool                   `protobuf:"varint,28,opt,name=remove_intermediate,json=removeIntermediate,proto3" json:"remove_intermediate,omitempty"`
	Quiet              bool                   `protobuf:"varint,29,opt,name=quiet,proto3" json:"quiet,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BuildOptions) Reset() {
	*x = BuildOptions{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildOptions) ProtoMessage() {}

func (x *BuildOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildOptions.ProtoReflect.Descriptor instead.
func (*BuildOptions) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *BuildOptions) GetContextDir() string {
	if x != nil {
		return x.ContextDir
	}
	return ""
}

func (x *BuildOptions) GetDockerfile() string {
	if x != nil {
		return x.Dockerfile
	}
	return ""
}

func (x *BuildOptions) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BuildOptions) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *BuildOptions) GetBuildArgs() []string {
	if x != nil {
		return x.BuildArgs
	}
	return nil
}

func (x *BuildOptions) GetSecrets() []string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *BuildOptions) GetCacheFrom() []string {
	if x != nil {
		return x.CacheFrom
	}
	return nil
}

func (x *BuildOptions) GetCacheTo() []string {
	if x != nil {
		return x.CacheTo
	}
	return nil
}

func (x *BuildOptions) GetPush() bool {
	if x != nil {
		return x.Push
	}
	return false
}

func (x *BuildOptions) GetLoad() bool {
	if x != nil {
		return x.Load
	}
	return false
}

func (x *BuildOptions) GetNoCache() bool {
	if x != nil {
		return x.NoCache
	}
	return false
}

func (x *BuildOptions) GetBuilder() string {
	if x != nil {
		return x.Builder
	}
	return ""
}

func (x *BuildOptions) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *BuildOptions) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *BuildOptions) GetInteractiveShell() string {
	if x != nil {
		return x.InteractiveShell
	}
	return ""
}

func (x *BuildOptions) GetBuildMode() string {
	if x != nil {
		return x.BuildMode
	}
	return ""
}

func (x *BuildOptions) GetComposeFiles() []string {
	if x != nil {
		return x.ComposeFiles
	}
	return nil
}

func (x *BuildOptions) GetComposeProfiles() []string {
	if x != nil {
		return x.ComposeProfiles
	}
	return nil
}

func (x *BuildOptions) GetComposeServices() []string {
	if x != nil {
		return x.ComposeServices
	}
	return nil
}

func (x *BuildOptions) GetComposeProject() string {
	if x != nil {
		return x.ComposeProject
	}
	return ""
}

func (x *BuildOptions) GetAuthFile() string {
	if x != nil {
		return x.AuthFile
	}
	return ""
}

func (x *BuildOptions) GetSandboxConfig() string {
	if x != nil {
		return x.SandboxConfig
	}
	return ""
}

func (x *BuildOptions) GetSandboxBin() string {
	if x != nil {
		return x.SandboxBin
	}
	return ""
}

func (x *BuildOptions) GetSandboxBinds() []string {
	if x != nil {
		return x.SandboxBinds
	}
	return nil
}

func (x *BuildOptions) GetSandboxWorkdir() string {
	if x != nil {
		return x.SandboxWorkdir
	}
	return ""
}

func (x *BuildOptions) GetSandboxLogs() bool {
	if x != nil {
		return x.SandboxLogs
	}
	return false
}

func (x *BuildOptions) GetLogFile() string {
	if x != nil {
		return x.LogFile
	}
	return ""
}

func (x *BuildOptions) GetRemoveIntermediate() bool {
	if x != nil {
		return x.RemoveIntermediate
	}
	return false
}

func (x *BuildOptions) GetQuiet() bool {
	if x != nil {
		return x.Quiet
	}
	return false
}

type RunBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *BuildOptions          `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Requester     string                 `protobuf:"bytes,3,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunBuildRequest) Reset() {
	*x = RunBuildRequest{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBuildRequest) ProtoMessage() {}

func (x *RunBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBuildRequest.ProtoReflect.Descriptor instead.
func (*RunBuildRequest) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RunBuildRequest) GetOptions() *BuildOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *RunBuildRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunBuildRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

type BuildResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	OciOutputDir  string                 `protobuf:"bytes,3,opt,name=oci_output_dir,json=ociOutputDir,proto3" json:"oci_output_dir,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResult) Reset() {
	*x = BuildResult{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResult) ProtoMessage() {}

func (x *BuildResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResult.ProtoReflect.Descriptor instead.
func (*BuildResult) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *BuildResult) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BuildResult) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *BuildResult) GetOciOutputDir() string {
	if x != nil {
		return x.OciOutputDir
	}
	return ""
}

func (x *BuildResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BuildEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNano int64                  `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*BuildEvent_Log
	//	*BuildEvent_Result
	Body          isBuildEvent_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEvent) Reset() {
	*x = BuildEvent{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent) ProtoMessage() {}

func (x *BuildEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent.ProtoReflect.Descriptor instead.
func (*BuildEvent) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *BuildEvent) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *BuildEvent) GetBody() isBuildEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *BuildEvent) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Body.(*BuildEvent_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *BuildEvent) GetResult() *BuildResult {
	if x != nil {
		if x, ok := x.Body.(*BuildEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isBuildEvent_Body interface {
	isBuildEvent_Body()
}

type BuildEvent_Log struct {
	Log *LogLine `protobuf:"bytes,2,opt,name=log,proto3,oneof"`
}

type BuildEvent_Result struct {
	Result *BuildResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*BuildEvent_Log) isBuildEvent_Body() {}

func (*BuildEvent_Result) isBuildEvent_Body() {}

type DeployEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployEvent) Reset() {
	*x = DeployEvent{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployEvent) ProtoMessage() {}

func (x *DeployEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployEvent.ProtoReflect.Descriptor instead.
func (*DeployEvent) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DeployEvent) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type DeployApplyOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Release         string                 `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Chart           string                 `protobuf:"bytes,2,opt,name=chart,proto3" json:"chart,omitempty"`
	Namespace       string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version         string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	ValuesFiles     []string               `protobuf:"bytes,5,rep,name=values_files,json=valuesFiles,proto3" json:"values_files,omitempty"`
	SetValues       []string               `protobuf:"bytes,6,rep,name=set_values,json=setValues,proto3" json:"set_values,omitempty"`
	SetStringValues []string               `protobuf:"bytes,7,rep,name=set_string_values,json=setStringValues,proto3" json:"set_string_values,omitempty"`
	SetFileValues   []string               `protobuf:"bytes,8,rep,name=set_file_values,json=setFileValues,proto3" json:"set_file_values,omitempty"`
	TimeoutSeconds  int64                  `protobuf:"varint,9,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Wait            bool                   `protobuf:"varint,10,opt,name=wait,proto3" json:"wait,omitempty"`
	Atomic          bool                   `protobuf:"varint,11,opt,name=atomic,proto3" json:"atomic,omitempty"`
	UpgradeOnly     bool                   `protobuf:"varint,12,opt,name=upgrade_only,json=upgradeOnly,proto3" json:"upgrade_only,omitempty"`
	CreateNamespace bool                   `protobuf:"varint,13,opt,name=create_namespace,json=createNamespace,proto3" json:"create_namespace,omitempty"`
	DryRun          bool                   `protobuf:"varint,14,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Diff            bool                   `protobuf:"varint,15,opt,name=diff,proto3" json:"diff,omitempty"`
	KubeContext     string                 `protobuf:"bytes,16,opt,name=kube_context,json=kubeContext,proto3" json:"kube_context,omitempty"`
	KubeconfigPath  string                 `protobuf:"bytes,17,opt,name=kubeconfig_path,json=kubeconfigPath,proto3" json:"kubeconfig_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeployApplyOptions) Reset() {
	*x = DeployApplyOptions{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployApplyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployApplyOptions) ProtoMessage() {}

func (x *DeployApplyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployApplyOptions.ProtoReflect.Descriptor instead.
func (*DeployApplyOptions) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DeployApplyOptions) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *DeployApplyOptions) GetChart() string {
	if x != nil {
		return x.Chart
	}
	return ""
}

func (x *DeployApplyOptions) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeployApplyOptions) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeployApplyOptions) GetValuesFiles() []string {
	if x != nil {
		return x.ValuesFiles
	}
	return nil
}

func (x *DeployApplyOptions) GetSetValues() []string {
	if x != nil {
		return x.SetValues
	}
	return nil
}

func (x *DeployApplyOptions) GetSetStringValues() []string {
	if x != nil {
		return x.SetStringValues
	}
	return nil
}

func (x *DeployApplyOptions) GetSetFileValues() []string {
	if x != nil {
		return x.SetFileValues
	}
	return nil
}

func (x *DeployApplyOptions) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *DeployApplyOptions) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

func (x *DeployApplyOptions) GetAtomic() bool {
	if x != nil {
		return x.Atomic
	}
	return false
}

func (x *DeployApplyOptions) GetUpgradeOnly() bool {
	if x != nil {
		return x.UpgradeOnly
	}
	return false
}

func (x *DeployApplyOptions) GetCreateNamespace() bool {
	if x != nil {
		return x.CreateNamespace
	}
	return false
}

func (x *DeployApplyOptions) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *DeployApplyOptions) GetDiff() bool {
	if x != nil {
		return x.Diff
	}
	return false
}

func (x *DeployApplyOptions) GetKubeContext() string {
	if x != nil {
		return x.KubeContext
	}
	return ""
}

func (x *DeployApplyOptions) GetKubeconfigPath() string {
	if x != nil {
		return x.KubeconfigPath
	}
	return ""
}

type DeployApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *DeployApplyOptions    `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployApplyRequest) Reset() {
	*x = DeployApplyRequest{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployApplyRequest) ProtoMessage() {}

func (x *DeployApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployApplyRequest.ProtoReflect.Descriptor instead.
func (*DeployApplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DeployApplyRequest) GetOptions() *DeployApplyOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type DeployDestroyOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Release        string                 `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Namespace      string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Wait           bool                   `protobuf:"varint,4,opt,name=wait,proto3" json:"wait,omitempty"`
	KeepHistory    bool                   `protobuf:"varint,5,opt,name=keep_history,json=keepHistory,proto3" json:"keep_history,omitempty"`
	DryRun         bool                   `protobuf:"varint,6,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Force          bool                   `protobuf:"varint,7,opt,name=force,proto3" json:"force,omitempty"`
	DisableHooks   bool                   `protobuf:"varint,8,opt,name=disable_hooks,json=disableHooks,proto3" json:"disable_hooks,omitempty"`
	KubeContext    string                 `protobuf:"bytes,9,opt,name=kube_context,json=kubeContext,proto3" json:"kube_context,omitempty"`
	KubeconfigPath string                 `protobuf:"bytes,10,opt,name=kubeconfig_path,json=kubeconfigPath,proto3" json:"kubeconfig_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeployDestroyOptions) Reset() {
	*x = DeployDestroyOptions{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployDestroyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployDestroyOptions) ProtoMessage() {}

func (x *DeployDestroyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployDestroyOptions.ProtoReflect.Descriptor instead.
func (*DeployDestroyOptions) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DeployDestroyOptions) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *DeployDestroyOptions) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeployDestroyOptions) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *DeployDestroyOptions) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

func (x *DeployDestroyOptions) GetKeepHistory() bool {
	if x != nil {
		return x.KeepHistory
	}
	return false
}

func (x *DeployDestroyOptions) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *DeployDestroyOptions) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *DeployDestroyOptions) GetDisableHooks() bool {
	if x != nil {
		return x.DisableHooks
	}
	return false
}

func (x *DeployDestroyOptions) GetKubeContext() string {
	if x != nil {
		return x.KubeContext
	}
	return ""
}

func (x *DeployDestroyOptions) GetKubeconfigPath() string {
	if x != nil {
		return x.KubeconfigPath
	}
	return ""
}

type DeployDestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *DeployDestroyOptions  `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployDestroyRequest) Reset() {
	*x = DeployDestroyRequest{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployDestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployDestroyRequest) ProtoMessage() {}

func (x *DeployDestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployDestroyRequest.ProtoReflect.Descriptor instead.
func (*DeployDestroyRequest) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DeployDestroyRequest) GetOptions() *DeployDestroyOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type MirrorFrame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Producer  string                 `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MirrorFrame_Log
	//	*MirrorFrame_Build
	//	*MirrorFrame_Deploy
	//	*MirrorFrame_Raw
	Payload       isMirrorFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MirrorFrame) Reset() {
	*x = MirrorFrame{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirrorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorFrame) ProtoMessage() {}

func (x *MirrorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorFrame.ProtoReflect.Descriptor instead.
func (*MirrorFrame) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *MirrorFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MirrorFrame) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *MirrorFrame) GetPayload() isMirrorFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MirrorFrame) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Payload.(*MirrorFrame_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *MirrorFrame) GetBuild() *BuildEvent {
	if x != nil {
		if x, ok := x.Payload.(*MirrorFrame_Build); ok {
			return x.Build
		}
	}
	return nil
}

func (x *MirrorFrame) GetDeploy() *DeployEvent {
	if x != nil {
		if x, ok := x.Payload.(*MirrorFrame_Deploy); ok {
			return x.Deploy
		}
	}
	return nil
}

func (x *MirrorFrame) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Payload.(*MirrorFrame_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isMirrorFrame_Payload interface {
	isMirrorFrame_Payload()
}

type MirrorFrame_Log struct {
	Log *LogLine `protobuf:"bytes,10,opt,name=log,proto3,oneof"`
}

type MirrorFrame_Build struct {
	Build *BuildEvent `protobuf:"bytes,11,opt,name=build,proto3,oneof"`
}

type MirrorFrame_Deploy struct {
	Deploy *DeployEvent `protobuf:"bytes,12,opt,name=deploy,proto3,oneof"`
}

type MirrorFrame_Raw struct {
	Raw []byte `protobuf:"bytes,13,opt,name=raw,proto3,oneof"`
}

func (*MirrorFrame_Log) isMirrorFrame_Payload() {}

func (*MirrorFrame_Build) isMirrorFrame_Payload() {}

func (*MirrorFrame_Deploy) isMirrorFrame_Payload() {}

func (*MirrorFrame_Raw) isMirrorFrame_Payload() {}

type MirrorAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MirrorAck) Reset() {
	*x = MirrorAck{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirrorAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorAck) ProtoMessage() {}

func (x *MirrorAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorAck.ProtoReflect.Descriptor instead.
func (*MirrorAck) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *MirrorAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MirrorAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MirrorAck) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type MirrorSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Replay        bool                   `protobuf:"varint,2,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MirrorSubscribeRequest) Reset() {
	*x = MirrorSubscribeRequest{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirrorSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorSubscribeRequest) ProtoMessage() {}

func (x *MirrorSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorSubscribeRequest.ProtoReflect.Descriptor instead.
func (*MirrorSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *MirrorSubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MirrorSubscribeRequest) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

type CaptureOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds int64                  `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	OutputName      string                 `protobuf:"bytes,2,opt,name=output_name,json=outputName,proto3" json:"output_name,omitempty"`
	Sqlite          bool                   `protobuf:"varint,3,opt,name=sqlite,proto3" json:"sqlite,omitempty"`
	AttachDescribe  bool                   `protobuf:"varint,4,opt,name=attach_describe,json=attachDescribe,proto3" json:"attach_describe,omitempty"`
	SessionName     string                 `protobuf:"bytes,5,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CaptureOptions) Reset() {
	*x = CaptureOptions{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureOptions) ProtoMessage() {}

func (x *CaptureOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureOptions.ProtoReflect.Descriptor instead.
func (*CaptureOptions) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *CaptureOptions) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *CaptureOptions) GetOutputName() string {
	if x != nil {
		return x.OutputName
	}
	return ""
}

func (x *CaptureOptions) GetSqlite() bool {
	if x != nil {
		return x.Sqlite
	}
	return false
}

func (x *CaptureOptions) GetAttachDescribe() bool {
	if x != nil {
		return x.AttachDescribe
	}
	return false
}

func (x *CaptureOptions) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type CaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *LogRequest            `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	Capture       *CaptureOptions        `protobuf:"bytes,2,opt,name=capture,proto3" json:"capture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *CaptureRequest) GetLog() *LogRequest {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *CaptureRequest) GetCapture() *CaptureOptions {
	if x != nil {
		return x.Capture
	}
	return nil
}

type CaptureChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Last          bool                   `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureChunk) Reset() {
	*x = CaptureChunk{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureChunk) ProtoMessage() {}

func (x *CaptureChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureChunk.ProtoReflect.Descriptor instead.
func (*CaptureChunk) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CaptureChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CaptureChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *CaptureChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CaptureChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DriftWatchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespaces      []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	AllNamespaces   bool                   `protobuf:"varint,2,opt,name=all_namespaces,json=allNamespaces,proto3" json:"all_namespaces,omitempty"`
	IntervalSeconds int64                  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	History         int32                  `protobuf:"varint,4,opt,name=history,proto3" json:"history,omitempty"`
	Iterations      int32                  `protobuf:"varint,5,opt,name=iterations,proto3" json:"iterations,omitempty"`
	KubeContext     string                 `protobuf:"bytes,6,opt,name=kube_context,json=kubeContext,proto3" json:"kube_context,omitempty"`
	KubeconfigPath  string                 `protobuf:"bytes,7,opt,name=kubeconfig_path,json=kubeconfigPath,proto3" json:"kubeconfig_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DriftWatchRequest) Reset() {
	*x = DriftWatchRequest{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftWatchRequest) ProtoMessage() {}

func (x *DriftWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftWatchRequest.ProtoReflect.Descriptor instead.
func (*DriftWatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *DriftWatchRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *DriftWatchRequest) GetAllNamespaces() bool {
	if x != nil {
		return x.AllNamespaces
	}
	return false
}

func (x *DriftWatchRequest) GetIntervalSeconds() int64 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *DriftWatchRequest) GetHistory() int32 {
	if x != nil {
		return x.History
	}
	return 0
}

func (x *DriftWatchRequest) GetIterations() int32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *DriftWatchRequest) GetKubeContext() string {
	if x != nil {
		return x.KubeContext
	}
	return ""
}

func (x *DriftWatchRequest) GetKubeconfigPath() string {
	if x != nil {
		return x.KubeconfigPath
	}
	return ""
}

type DriftEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftEvent) Reset() {
	*x = DriftEvent{}
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftEvent) ProtoMessage() {}

func (x *DriftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ktl_api_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftEvent.ProtoReflect.Descriptor instead.
func (*DriftEvent) Descriptor() ([]byte, []int) {
	return file_proto_ktl_api_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *DriftEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_proto_ktl_api_v1_agent_proto protoreflect.FileDescriptor

const file_proto_ktl_api_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/ktl/api/v1/agent.proto\x12\n" +
	"ktl.api.v1\"\xe0\x04\n" +
	"\n" +
	"LogRequest\x12\x1b\n" +
	"\tpod_query\x18\x01 \x01(\tR\bpodQuery\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\tR\n" +
	"namespaces\x12%\n" +
	"\x0eall_namespaces\x18\x03 \x01(\bR\rallNamespaces\x12%\n" +
	"\x0elabel_selector\x18\x04 \x01(\tR\rlabelSelector\x12%\n" +
	"\x0efield_selector\x18\x05 \x01(\tR\rfieldSelector\x12\x1e\n" +
	"\n" +
	"containers\x18\x06 \x03(\tR\n" +
	"containers\x12-\n" +
	"\x12exclude_containers\x18\a \x03(\tR\x11excludeContainers\x12!\n" +
	"\fexclude_pods\x18\b \x03(\tR\vexcludePods\x12'\n" +
	"\x0fhighlight_terms\x18\t \x03(\tR\x0ehighlightTerms\x12%\n" +
	"\x0einclude_events\x18\n" +
	" \x01(\bR\rincludeEvents\x12\x1f\n" +
	"\vevents_only\x18\v \x01(\bR\n" +
	"eventsOnly\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\f \x01(\x03R\ttailLines\x12\x16\n" +
	"\x06follow\x18\r \x01(\bR\x06follow\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x0e \x01(\bR\n" +
	"timestamps\x12\x1a\n" +
	"\btemplate\x18\x0f \x01(\tR\btemplate\x12!\n" +
	"\fkube_context\x18\x10 \x01(\tR\vkubeContext\x12'\n" +
	"\x0fkubeconfig_path\x18\x11 \x01(\tR\x0ekubeconfigPath\"\xd1\x02\n" +
	"\aLogLine\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12/\n" +
	"\x13formatted_timestamp\x18\x02 \x01(\tR\x12formattedTimestamp\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x04 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x05 \x01(\tR\tcontainer\x12\x10\n" +
	"\x03raw\x18\x06 \x01(\tR\x03raw\x12\x1a\n" +
	"\brendered\x18\a \x01(\tR\brendered\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12!\n" +
	"\fsource_glyph\x18\t \x01(\tR\vsourceGlyph\x12.\n" +
	"\x13rendered_equals_raw\x18\n" +
	" \x01(\bR\x11renderedEqualsRaw\"\xb8\a\n" +
	"\fBuildOptions\x12\x1f\n" +
	"\vcontext_dir\x18\x01 \x01(\tR\n" +
	"contextDir\x12\x1e\n" +
	"\n" +
	"dockerfile\x18\x02 \x01(\tR\n" +
	"dockerfile\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1c\n" +
	"\tplatforms\x18\x04 \x03(\tR\tplatforms\x12\x1d\n" +
	"\n" +
	"build_args\x18\x05 \x03(\tR\tbuildArgs\x12\x18\n" +
	"\asecrets\x18\x06 \x03(\tR\asecrets\x12\x1d\n" +
	"\n" +
	"cache_from\x18\a \x03(\tR\tcacheFrom\x12\x19\n" +
	"\bcache_to\x18\b \x03(\tR\acacheTo\x12\x12\n" +
	"\x04push\x18\t \x01(\bR\x04push\x12\x12\n" +
	"\x04load\x18\n" +
	" \x01(\bR\x04load\x12\x19\n" +
	"\bno_cache\x18\v \x01(\bR\anoCache\x12\x18\n" +
	"\abuilder\x18\f \x01(\tR\abuilder\x12\x1b\n" +
	"\tcache_dir\x18\r \x01(\tR\bcacheDir\x12 \n" +
	"\vinteractive\x18\x0e \x01(\bR\vinteractive\x12+\n" +
	"\x11interactive_shell\x18\x0f \x01(\tR\x10interactiveShell\x12\x1d\n" +
	"\n" +
	"build_mode\x18\x10 \x01(\tR\tbuildMode\x12#\n" +
	"\rcompose_files\x18\x11 \x03(\tR\fcomposeFiles\x12)\n" +
	"\x10compose_profiles\x18\x12 \x03(\tR\x0fcomposeProfiles\x12)\n" +
	"\x10compose_services\x18\x13 \x03(\tR\x0fcomposeServices\x12'\n" +
	"\x0fcompose_project\x18\x14 \x01(\tR\x0ecomposeProject\x12\x1b\n" +
	"\tauth_file\x18\x15 \x01(\tR\bauthFile\x12%\n" +
	"\x0esandbox_config\x18\x16 \x01(\tR\rsandboxConfig\x12\x1f\n" +
	"\vsandbox_bin\x18\x17 \x01(\tR\n" +
	"sandboxBin\x12#\n" +
	"\rsandbox_binds\x18\x18 \x03(\tR\fsandboxBinds\x12'\n" +
	"\x0fsandbox_workdir\x18\x19 \x01(\tR\x0esandboxWorkdir\x12!\n" +
	"\fsandbox_logs\x18\x1a \x01(\bR\vsandboxLogs\x12\x19\n" +
	"\blog_file\x18\x1b \x01(\tR\alogFile\x12/\n" +
	"\x13remove_intermediate\x18\x1c \x01(\bR\x12removeIntermediate\x12\x14\n" +
	"\x05quiet\x18\x1d \x01(\bR\x05quiet\"\x82\x01\n" +
	"\x0fRunBuildRequest\x122\n" +
	"\aoptions\x18\x01 \x01(\v2\x18.ktl.api.v1.BuildOptionsR\aoptions\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1c\n" +
	"\trequester\x18\x03 \x01(\tR\trequester\"u\n" +
	"\vBuildResult\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12$\n" +
	"\x0eoci_output_dir\x18\x03 \x01(\tR\fociOutputDir\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xa0\x01\n" +
	"\n" +
	"BuildEvent\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12'\n" +
	"\x03log\x18\x02 \x01(\v2\x13.ktl.api.v1.LogLineH\x00R\x03log\x121\n" +
	"\x06result\x18\x03 \x01(\v2\x17.ktl.api.v1.BuildResultH\x00R\x06resultB\x06\n" +
	"\x04body\"!\n" +
	"\vDeployEvent\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"\xae\x04\n" +
	"\x12DeployApplyOptions\x12\x18\n" +
	"\arelease\x18\x01 \x01(\tR\arelease\x12\x14\n" +
	"\x05chart\x18\x02 \x01(\tR\x05chart\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12!\n" +
	"\fvalues_files\x18\x05 \x03(\tR\vvaluesFiles\x12\x1d\n" +
	"\n" +
	"set_values\x18\x06 \x03(\tR\tsetValues\x12*\n" +
	"\x11set_string_values\x18\a \x03(\tR\x0fsetStringValues\x12&\n" +
	"\x0fset_file_values\x18\b \x03(\tR\rsetFileValues\x12'\n" +
	"\x0ftimeout_seconds\x18\t \x01(\x03R\x0etimeoutSeconds\x12\x12\n" +
	"\x04wait\x18\n" +
	" \x01(\bR\x04wait\x12\x16\n" +
	"\x06atomic\x18\v \x01(\bR\x06atomic\x12!\n" +
	"\fupgrade_only\x18\f \x01(\bR\vupgradeOnly\x12)\n" +
	"\x10create_namespace\x18\r \x01(\bR\x0fcreateNamespace\x12\x17\n" +
	"\adry_run\x18\x0e \x01(\bR\x06dryRun\x12\x12\n" +
	"\x04diff\x18\x0f \x01(\bR\x04diff\x12!\n" +
	"\fkube_context\x18\x10 \x01(\tR\vkubeContext\x12'\n" +
	"\x0fkubeconfig_path\x18\x11 \x01(\tR\x0ekubeconfigPath\"N\n" +
	"\x12DeployApplyRequest\x128\n" +
	"\aoptions\x18\x01 \x01(\v2\x1e.ktl.api.v1.DeployApplyOptionsR\aoptions\"\xce\x02\n" +
	"\x14DeployDestroyOptions\x12\x18\n" +
	"\arelease\x18\x01 \x01(\tR\arelease\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x03R\x0etimeoutSeconds\x12\x12\n" +
	"\x04wait\x18\x04 \x01(\bR\x04wait\x12!\n" +
	"\fkeep_history\x18\x05 \x01(\bR\vkeepHistory\x12\x17\n" +
	"\adry_run\x18\x06 \x01(\bR\x06dryRun\x12\x14\n" +
	"\x05force\x18\a \x01(\bR\x05force\x12#\n" +
	"\rdisable_hooks\x18\b \x01(\bR\fdisableHooks\x12!\n" +
	"\fkube_context\x18\t \x01(\tR\vkubeContext\x12'\n" +
	"\x0fkubeconfig_path\x18\n" +
	" \x01(\tR\x0ekubeconfigPath\"R\n" +
	"\x14DeployDestroyRequest\x12:\n" +
	"\aoptions\x18\x01 \x01(\v2 .ktl.api.v1.DeployDestroyOptionsR\aoptions\"\xf3\x01\n" +
	"\vMirrorFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bproducer\x18\x02 \x01(\tR\bproducer\x12'\n" +
	"\x03log\x18\n" +
	" \x01(\v2\x13.ktl.api.v1.LogLineH\x00R\x03log\x12.\n" +
	"\x05build\x18\v \x01(\v2\x16.ktl.api.v1.BuildEventH\x00R\x05build\x121\n" +
	"\x06deploy\x18\f \x01(\v2\x17.ktl.api.v1.DeployEventH\x00R\x06deploy\x12\x12\n" +
	"\x03raw\x18\r \x01(\fH\x00R\x03rawB\t\n" +
	"\apayload\"`\n" +
	"\tMirrorAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\"O\n" +
	"\x16MirrorSubscribeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06replay\x18\x02 \x01(\bR\x06replay\"\xc0\x01\n" +
	"\x0eCaptureOptions\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\x03R\x0fdurationSeconds\x12\x1f\n" +
	"\voutput_name\x18\x02 \x01(\tR\n" +
	"outputName\x12\x16\n" +
	"\x06sqlite\x18\x03 \x01(\bR\x06sqlite\x12'\n" +
	"\x0fattach_describe\x18\x04 \x01(\bR\x0eattachDescribe\x12!\n" +
	"\fsession_name\x18\x05 \x01(\tR\vsessionName\"p\n" +
	"\x0eCaptureRequest\x12(\n" +
	"\x03log\x18\x01 \x01(\v2\x16.ktl.api.v1.LogRequestR\x03log\x124\n" +
	"\acapture\x18\x02 \x01(\v2\x1a.ktl.api.v1.CaptureOptionsR\acapture\"h\n" +
	"\fCaptureChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x02 \x01(\bR\x04last\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8b\x02\n" +
	"\x11DriftWatchRequest\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12%\n" +
	"\x0eall_namespaces\x18\x02 \x01(\bR\rallNamespaces\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\x03R\x0fintervalSeconds\x12\x18\n" +
	"\ahistory\x18\x04 \x01(\x05R\ahistory\x12\x1e\n" +
	"\n" +
	"iterations\x18\x05 \x01(\x05R\n" +
	"iterations\x12!\n" +
	"\fkube_context\x18\x06 \x01(\tR\vkubeContext\x12'\n" +
	"\x0fkubeconfig_path\x18\a \x01(\tR\x0ekubeconfigPath\" \n" +
	"\n" +
	"DriftEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2I\n" +
	"\n" +
	"LogService\x12;\n" +
	"\n" +
	"StreamLogs\x12\x16.ktl.api.v1.LogRequest\x1a\x13.ktl.api.v1.LogLine0\x012Q\n" +
	"\fBuildService\x12A\n" +
	"\bRunBuild\x12\x1b.ktl.api.v1.RunBuildRequest\x1a\x16.ktl.api.v1.BuildEvent0\x012\x9b\x01\n" +
	"\rDeployService\x12B\n" +
	"\x05Apply\x12\x1e.ktl.api.v1.DeployApplyRequest\x1a\x17.ktl.api.v1.DeployEvent0\x01\x12F\n" +
	"\aDestroy\x12 .ktl.api.v1.DeployDestroyRequest\x1a\x17.ktl.api.v1.DeployEvent0\x012\x9a\x01\n" +
	"\rMirrorService\x12=\n" +
	"\aPublish\x12\x17.ktl.api.v1.MirrorFrame\x1a\x15.ktl.api.v1.MirrorAck(\x010\x01\x12J\n" +
	"\tSubscribe\x12\".ktl.api.v1.MirrorSubscribeRequest\x1a\x17.ktl.api.v1.MirrorFrame0\x012V\n" +
	"\x0eCaptureService\x12D\n" +
	"\n" +
	"RunCapture\x12\x1a.ktl.api.v1.CaptureRequest\x1a\x18.ktl.api.v1.CaptureChunk0\x012P\n" +
	"\fDriftService\x12@\n" +
	"\x05Watch\x12\x1d.ktl.api.v1.DriftWatchRequest\x1a\x16.ktl.api.v1.DriftEvent0\x01B)Z'github.com/example/ktl/pkg/api/v1;apiv1b\x06proto3"

var (
	file_proto_ktl_api_v1_agent_proto_rawDescOnce sync.Once
	file_proto_ktl_api_v1_agent_proto_rawDescData []byte
)

func file_proto_ktl_api_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_ktl_api_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_ktl_api_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ktl_api_v1_agent_proto_rawDesc), len(file_proto_ktl_api_v1_agent_proto_rawDesc)))
	})
	return file_proto_ktl_api_v1_agent_proto_rawDescData
}

var file_proto_ktl_api_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_ktl_api_v1_agent_proto_goTypes = []any{
	(*LogRequest)(nil),             // 0: ktl.api.v1.LogRequest
	(*LogLine)(nil),                // 1: ktl.api.v1.LogLine
	(*BuildOptions)(nil),           // 2: ktl.api.v1.BuildOptions
	(*RunBuildRequest)(nil),        // 3: ktl.api.v1.RunBuildRequest
	(*BuildResult)(nil),            // 4: ktl.api.v1.BuildResult
	(*BuildEvent)(nil),             // 5: ktl.api.v1.BuildEvent
	(*DeployEvent)(nil),            // 6: ktl.api.v1.DeployEvent
	(*DeployApplyOptions)(nil),     // 7: ktl.api.v1.DeployApplyOptions
	(*DeployApplyRequest)(nil),     // 8: ktl.api.v1.DeployApplyRequest
	(*DeployDestroyOptions)(nil),   // 9: ktl.api.v1.DeployDestroyOptions
	(*DeployDestroyRequest)(nil),   // 10: ktl.api.v1.DeployDestroyRequest
	(*MirrorFrame)(nil),            // 11: ktl.api.v1.MirrorFrame
	(*MirrorAck)(nil),              // 12: ktl.api.v1.MirrorAck
	(*MirrorSubscribeRequest)(nil), // 13: ktl.api.v1.MirrorSubscribeRequest
	(*CaptureOptions)(nil),         // 14: ktl.api.v1.CaptureOptions
	(*CaptureRequest)(nil),         // 15: ktl.api.v1.CaptureRequest
	(*CaptureChunk)(nil),           // 16: ktl.api.v1.CaptureChunk
	(*DriftWatchRequest)(nil),      // 17: ktl.api.v1.DriftWatchRequest
	(*DriftEvent)(nil),             // 18: ktl.api.v1.DriftEvent
}
var file_proto_ktl_api_v1_agent_proto_depIdxs = []int32{
	2,  // 0: ktl.api.v1.RunBuildRequest.options:type_name -> ktl.api.v1.BuildOptions
	1,  // 1: ktl.api.v1.BuildEvent.log:type_name -> ktl.api.v1.LogLine
	4,  // 2: ktl.api.v1.BuildEvent.result:type_name -> ktl.api.v1.BuildResult
	7,  // 3: ktl.api.v1.DeployApplyRequest.options:type_name -> ktl.api.v1.DeployApplyOptions
	9,  // 4: ktl.api.v1.DeployDestroyRequest.options:type_name -> ktl.api.v1.DeployDestroyOptions
	1,  // 5: ktl.api.v1.MirrorFrame.log:type_name -> ktl.api.v1.LogLine
	5,  // 6: ktl.api.v1.MirrorFrame.build:type_name -> ktl.api.v1.BuildEvent
	6,  // 7: ktl.api.v1.MirrorFrame.deploy:type_name -> ktl.api.v1.DeployEvent
	0,  // 8: ktl.api.v1.CaptureRequest.log:type_name -> ktl.api.v1.LogRequest
	14, // 9: ktl.api.v1.CaptureRequest.capture:type_name -> ktl.api.v1.CaptureOptions
	0,  // 10: ktl.api.v1.LogService.StreamLogs:input_type -> ktl.api.v1.LogRequest
	3,  // 11: ktl.api.v1.BuildService.RunBuild:input_type -> ktl.api.v1.RunBuildRequest
	8,  // 12: ktl.api.v1.DeployService.Apply:input_type -> ktl.api.v1.DeployApplyRequest
	10, // 13: ktl.api.v1.DeployService.Destroy:input_type -> ktl.api.v1.DeployDestroyRequest
	11, // 14: ktl.api.v1.MirrorService.Publish:input_type -> ktl.api.v1.MirrorFrame
	13, // 15: ktl.api.v1.MirrorService.Subscribe:input_type -> ktl.api.v1.MirrorSubscribeRequest
	15, // 16: ktl.api.v1.CaptureService.RunCapture:input_type -> ktl.api.v1.CaptureRequest
	17, // 17: ktl.api.v1.DriftService.Watch:input_type -> ktl.api.v1.DriftWatchRequest
	1,  // 18: ktl.api.v1.LogService.StreamLogs:output_type -> ktl.api.v1.LogLine
	5,  // 19: ktl.api.v1.BuildService.RunBuild:output_type -> ktl.api.v1.BuildEvent
	6,  // 20: ktl.api.v1.DeployService.Apply:output_type -> ktl.api.v1.DeployEvent
	6,  // 21: ktl.api.v1.DeployService.Destroy:output_type -> ktl.api.v1.DeployEvent
	12, // 22: ktl.api.v1.MirrorService.Publish:output_type -> ktl.api.v1.MirrorAck
	11, // 23: ktl.api.v1.MirrorService.Subscribe:output_type -> ktl.api.v1.MirrorFrame
	16, // 24: ktl.api.v1.CaptureService.RunCapture:output_type -> ktl.api.v1.CaptureChunk
	18, // 25: ktl.api.v1.DriftService.Watch:output_type -> ktl.api.v1.DriftEvent
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_ktl_api_v1_agent_proto_init() }
func file_proto_ktl_api_v1_agent_proto_init() {
	if File_proto_ktl_api_v1_agent_proto != nil {
		return
	}
	file_proto_ktl_api_v1_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*BuildEvent_Log)(nil),
		(*BuildEvent_Result)(nil),
	}
	file_proto_ktl_api_v1_agent_proto_msgTypes[11].OneofWrappers = []any{
		(*MirrorFrame_Log)(nil),
		(*MirrorFrame_Build)(nil),
		(*MirrorFrame_Deploy)(nil),
		(*MirrorFrame_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ktl_api_v1_agent_proto_rawDesc), len(file_proto_ktl_api_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_proto_ktl_api_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_ktl_api_v1_agent_proto_depIdxs,
		MessageInfos:      file_proto_ktl_api_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_ktl_api_v1_agent_proto = out.File
	file_proto_ktl_api_v1_agent_proto_goTypes = nil
	file_proto_ktl_api_v1_agent_proto_depIdxs = nil
}
