FROM python:3.12-slim

WORKDIR /opt/app
COPY app/payment_api.py /opt/app/payment_api.py
RUN python -m pip install --no-cache-dir \
    fastapi \
    uvicorn \
    boto3 \
    kafka-python \
    requests \
    clickhouse-connect \
    opentelemetry-sdk \
    opentelemetry-exporter-otlp-proto-http

EXPOSE 8080
CMD ["uvicorn", "payment_api:app", "--host", "0.0.0.0", "--port", "8080", "--app-dir", "/opt/app"]
