FROM apache/spark:4.1.2-scala2.13-java17-python3-ubuntu

USER root
WORKDIR /opt/app
COPY app/spark_batch.py /opt/app/spark_batch.py
RUN python -m pip install --no-cache-dir boto3 clickhouse-connect

CMD ["/opt/spark/bin/spark-submit", "--packages", "org.apache.iceberg:iceberg-spark-runtime-4.0_2.13:1.10.1,org.apache.iceberg:iceberg-aws-bundle:1.10.1", "/opt/app/spark_batch.py"]
